version: "3.1"
services:

  webserver:
    image: nginx:alpine
    container_name: world-check-webserver
    working_dir: /application
    volumes:
        - ./laravel:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - mariadb
      - php-fpm
      - redis

  redis:
    image: redis:alpine
    container_name: world-check-redis

  mariadb:
    image: mariadb:10.1
    container_name: world-check-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "1028:3306"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: world-check-php-fpm
    working_dir: /application
    volumes:
      - ./laravel:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini